name: weather_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter_typeahead: ^4.1.0
  intl: ^0.17.0
  flutter_bloc: ^8.1.1
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter_hooks: ^0.18.5+1
  bloc: ^8.1.0
  equatable: ^2.0.5
  floor: ^1.3.0
  retrofit: ^3.0.1+1
  get_it: ^7.2.0
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.5
  fl_chart: ^0.55.1
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0

dev_dependencies:
  retrofit_generator: '<5.0.0'
  build_runner: ^2.2.0
  floor_generator: ^1.3.0
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.1

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - lib/core/resources/assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
